Refactoring

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI Available
+name: _CI Available
 
 on: 
   pull_request:
@@ -13,9 +13,9 @@ jobs:
     steps:
     - uses: actions/checkout@v1
 
-    : # 
-    - name: CI unavailable now
-      run: exit 1
+    : # Uncomment next lines to let developers know that CI failed
+    : # - name: CI unavailable now
+    : #   run: exit 1
     : # 
     - name: CI available
       run: echo If you see blinking test please let DevOps know
