implement: dte

diff --git a/.github/workflows/default_workflow.yml b/.github/workflows/default_workflow.yml
--- a/.github/workflows/default_workflow.yml
+++ b/.github/workflows/default_workflow.yml
@@ -13,17 +13,27 @@ on:
       - "[0-9][0-9]_[0-9]"
 
 env:
+  NX_CLOUD_DISTRIBUTED_EXECUTION: true # this enables DTE
+  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3 # expected number of agents
+  NX_BRANCH: ${{ github.event.number || github.ref_name }}
+  # NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
+  # NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # this is needed if our pipeline publishes to npm  
   NX_SKIP_NX_CACHE: ${{ (github.event_name != 'pull_request' || contains( github.event.pull_request.labels.*.name, 'skip-cache')) && 'true' || 'false' }}
 
 jobs:
   main:
     name: main
     runs-on: devextreme-shr2
-    timeout-minutes: 30
+    timeout-minutes: 90
 
     steps:
     - name: Get sources
       uses: actions/checkout@v4
+
+    - name: Setup Chrome
+      uses: ./.github/actions/setup-chrome
+      with:
+        chrome-version: '133.0.6943.53'
 
     - name: Use Node.js
       uses: actions/setup-node@v4
@@ -52,6 +62,36 @@ jobs:
     - name: Install dependencies
       run: pnpm install --frozen-lockfile
 
+    - name: Initialize the Nx Cloud distributed CI run and stop agents when the build tasks are done
+      run: pnpm nx-cloud start-ci-run --distribute-on="manual"
+
+    # - name: Run commands in parallel
+    #   run: |
+    #     # initialize an array to store process IDs (PIDs)
+    #     pids=()
+
+    #     # function to run commands and store the PID
+    #     function run_command() {
+    #       local command=$1
+    #       $command &  # run the command in the background
+    #       pids+=($!)  # store the PID of the background process
+    #     }
+
+    #     # list of commands to be run on main has env flag NX_CLOUD_DISTRIBUTED_EXECUTION set to false
+    #     # run_command "NX_CLOUD_DISTRIBUTED_EXECUTION=false pnpm nx-cloud record -- nx format:check"
+
+    #     # list of commands to be run on agents
+    #     run_command "pnpm nx run-many --targets test,e2e --exclude devextreme devextreme-themebuilder devextreme-angular devextreme-react devextreme-vue devextreme-react-storybook devextreme-main devextreme-angular-playground devextreme-demos devextreme-react-playground devextreme-vue-playground"
+
+    #     # wait for all background processes to finish
+    #     for pid in ${pids[*]}; do
+    #       if ! wait $pid; then
+    #         exit 1  # exit with an error status if any process fails
+    #       fi
+    #     done
+
+    #     exit 0 # exits with success status if a all processes complete successfully
+
     - name: Run targets
       run: >
         pnpx nx run-many
@@ -68,3 +108,52 @@ jobs:
         devextreme-demos
         devextreme-react-playground
         devextreme-vue-playground
+
+  agents:
+    name: Agent ${{ matrix.agent }}
+    runs-on: devextreme-shr2
+    strategy:
+      matrix:
+        # Add more agents here as your repository expands
+        agent: [1, 2, 3]
+    steps:
+      - name: Get sources
+        uses: actions/checkout@v4
+
+      - name: Setup Chrome
+        uses: ./.github/actions/setup-chrome
+        with:
+          chrome-version: '133.0.6943.53'
+
+      - name: Use Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+
+      - uses: pnpm/action-setup@v3
+        with:
+          version: 9
+          run_install: false
+
+      - name: Get pnpm store directory
+        shell: bash
+        run: |
+          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
+
+      - uses: actions/cache@v4
+        name: Setup pnpm cache
+        with:
+          path: |
+            ${{ env.STORE_PATH }}
+            .nx/cache
+          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-pnpm-store
+
+      - name: Install dependencies
+        run: pnpm install
+
+      - name: Start Nx Agent ${{ matrix.agent }}
+        run: pnpm nx-cloud start-agent
+        env:
+          NX_AGENT_NAME: ${{ matrix.agent }}
