Move declarations test to GA

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -66,6 +66,27 @@ jobs:
     - name: Lint .d.ts
       run: npm run lint-dts
 
+    - name: Validate declarations
+      run: |
+        target=./ts/dx.all.d.ts
+        cp $target $target.current
+
+        npm update devextreme-internal-tools
+        npm ls devextreme-internal-tools || :
+        
+        npm run validate-declarations
+        npm run update-ts
+        
+        if ! diff $target.current $target -U 5 > $target.diff; then
+            echo "FAIL: $target is outdated:"
+            cat $target.diff | sed "1,2d"
+            exit 1
+        else
+            echo "TS is up-to-date"
+        fi
+        
+        npm run validate-ts
+
   JS:
     runs-on: ubuntu-latest
     timeout-minutes: 60
