fix: move using diff file

diff --git a/.github/workflows/wrapper_tests.yml b/.github/workflows/wrapper_tests.yml
--- a/.github/workflows/wrapper_tests.yml
+++ b/.github/workflows/wrapper_tests.yml
@@ -109,25 +109,20 @@ jobs:
           paths: 'packages/devextreme-*/src/**'
           output: diff.json
 
-      - name: Debug diff.json
-        run: |
-          cat diff.json || echo "No diff.json"
-
-      - name: Debug changed count
-        run: |
-          echo "Changed count: ${{ steps.check-diff.outputs.count }}"
-          echo "Changed files: ${{ steps.check-diff.outputs.files }}"
-
       - name: Fail if generated code is outdated
-        if: ${{ steps.check-diff.outputs.count > 0 }}
         shell: bash
         run: |
-          echo "Generated code is outdated. The following files have uncommitted changes:"
-          echo "${{ steps.check-diff.outputs.files }}" | tr -d "'" | tr ' ' '\n' | while read -r file; do
-            echo "::error file=$file::Generated file is outdated"
-          done
-          echo "Please, update generated code and commit changes."
-          exit 1
+          count=$(jq length diff.json)
+          if [ "$count" -gt 0 ]; then
+            echo "Generated code is outdated. The following files have uncommitted changes:"
+            jq -r '.[].filename' diff.json | while read -r file; do
+              echo "::error file=$file::Generated file is outdated"
+            done
+            echo "To update generated code, use "pnpm run regenerate-all" and commit changes."
+            exit 1
+          else
+            echo "No changes in generated code."
+          fi
         
   test:
     runs-on: devextreme-shr2
