fix: review fixes

diff --git a/.github/workflows/wrapper_tests.yml b/.github/workflows/wrapper_tests.yml
--- a/.github/workflows/wrapper_tests.yml
+++ b/.github/workflows/wrapper_tests.yml
@@ -1,4 +1,4 @@
-name: DevExtreme Wrappers Tests
+name: Wrappers Tests
 
 on:
   pull_request:
@@ -57,7 +57,7 @@ jobs:
 
   check-regenerate:
     runs-on: devextreme-shr2
-    timeout-minutes: 80
+    timeout-minutes: 10
 
     steps:
       - name: Get sources
@@ -102,18 +102,34 @@ jobs:
           paths: 'packages/devextreme-*/src/**'
           output: changed-files.json
 
+      # - name: Fail if generated code is outdated
+      #   shell: bash
+      #   run: |
+      #     if [ -s changed-files.json ]; then
+      #       echo "Generated code is outdated. The following files were changed:"
+      #       cat changed-files.json | jq -r '.[]'
+      #       echo ""
+      #       echo "To update generated code, run: pnpm run regenerate-all"
+      #       exit 1
+      #     else
+      #       echo "No changes in generated code."
+      #     fi
+
       - name: Fail if generated code is outdated
         shell: bash
         run: |
-          if [ -s changed-files.json ]; then
-            echo "Generated code is outdated. The following files were changed:"
-            cat changed-files.json | jq -r '.[]'
-            echo ""
-            echo "To update generated code, run: pnpm run regenerate-all"
-            exit 1
+          if ${{ steps.check-diff.outputs.count > 0 }}; then
+            echo ${{ steps.check-diff.outputs.files }}
           else
             echo "No changes in generated code."
           fi
+
+      - name: Archive devextreme-metadata artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: devextreme-metadata-artifacts
+          path: packages/devextreme-metadata/dist/
+          retention-days: 7
 
   test:
     runs-on: devextreme-shr2
@@ -155,24 +171,18 @@ jobs:
       - name: Install dependencies
         run: pnpm install
 
+      - name: Build wrappers
+        run: pnpx nx build devextreme-${{ matrix.framework }}
+
       - name: Build and Test ${{ matrix.framework }}
         run: |
           if [ "${{ matrix.framework }}" = "angular" ]; then
-            pnpx nx build devextreme-angular
             pnpx nx test:dev devextreme-angular
             pnpx nx pack devextreme-angular
           elif [ "${{ matrix.framework }}" = "react" ]; then
-            pnpm exec nx test devextreme-react
-            pnpm exec nx pack devextreme-react
+            pnpx nx test devextreme-react
+            pnpx nx pack devextreme-react
           elif [ "${{ matrix.framework }}" = "vue" ]; then
             pnpx nx test devextreme-vue
             pnpx nx pack devextreme-vue
           fi
-
-      - name: Archive devextreme-metadata artifacts
-        if: matrix.framework == 'angular'
-        uses: actions/upload-artifact@v4
-        with:
-          name: devextreme-metadata-artifacts
-          path: packages/devextreme-metadata/dist/
-          retention-days: 7
